import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

const _kLocaleStorageKey = '__locale_key__';

class FFLocalizations {
  FFLocalizations(this.locale);

  final Locale locale;

  static FFLocalizations of(BuildContext context) =>
      Localizations.of<FFLocalizations>(context, FFLocalizations)!;

  static List<String> languages() => ['es', 'en', 'ru', 'zh_Hant', 'it', 'fr'];

  static late SharedPreferences _prefs;
  static Future initialize() async =>
      _prefs = await SharedPreferences.getInstance();
  static Future storeLocale(String locale) =>
      _prefs.setString(_kLocaleStorageKey, locale);
  static Locale? getStoredLocale() {
    final locale = _prefs.getString(_kLocaleStorageKey);
    return locale != null && locale.isNotEmpty ? createLocale(locale) : null;
  }

  String get languageCode => locale.toString();
  String? get languageShortCode =>
      _languagesWithShortCode.contains(locale.toString())
          ? '${locale.toString()}_short'
          : null;
  int get languageIndex => languages().contains(languageCode)
      ? languages().indexOf(languageCode)
      : 0;

  String getText(String key) =>
      (kTranslationsMap[key] ?? {})[locale.toString()] ?? '';

  String getVariableText({
    String? esText = '',
    String? enText = '',
    String? ruText = '',
    String? zh_HantText = '',
    String? itText = '',
    String? frText = '',
  }) =>
      [esText, enText, ruText, zh_HantText, itText, frText][languageIndex] ??
      '';

  static const Set<String> _languagesWithShortCode = {
    'ar',
    'az',
    'ca',
    'cs',
    'da',
    'de',
    'dv',
    'en',
    'es',
    'et',
    'fi',
    'fr',
    'gr',
    'he',
    'hi',
    'hu',
    'it',
    'km',
    'ku',
    'mn',
    'ms',
    'no',
    'pt',
    'ro',
    'ru',
    'rw',
    'sv',
    'th',
    'uk',
    'vi',
  };
}

class FFLocalizationsDelegate extends LocalizationsDelegate<FFLocalizations> {
  const FFLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    final language = locale.toString();
    return FFLocalizations.languages().contains(
      language.endsWith('_')
          ? language.substring(0, language.length - 1)
          : language,
    );
  }

  @override
  Future<FFLocalizations> load(Locale locale) =>
      SynchronousFuture<FFLocalizations>(FFLocalizations(locale));

  @override
  bool shouldReload(FFLocalizationsDelegate old) => false;
}

Locale createLocale(String language) => language.contains('_')
    ? Locale.fromSubtags(
        languageCode: language.split('_').first,
        scriptCode: language.split('_').last,
      )
    : Locale(language);

final kTranslationsMap = <Map<String, Map<String, String>>>[
  // Login
  {
    'u6kw9aif': {
      'es': 'Ingresar',
      'en': 'Login',
      'fr': 'Entrer dans',
      'it': 'Entrare dentro',
      'ru': 'Попасть в',
      'zh_Hant': '進入',
    },
    'alqkhtxs': {
      'es': 'Ingrese su dirección de correo electrónico',
      'en': 'Enter your email address',
      'fr': 'Entrez votre adresse email',
      'it': 'Inserisci il tuo indirizzo email',
      'ru': 'Введите ваш адрес электронной почты',
      'zh_Hant': '輸入你的電子郵箱地址',
    },
    'ku047vvz': {
      'es': 'Ejm: xio@gmail.com',
      'en': 'Example: xio@gmail.com',
      'fr': 'Exemple : xio@gmail.com',
      'it': 'Esempio: xio@gmail.com',
      'ru': 'Пример: xio@gmail.com',
      'zh_Hant': '示例：xio@gmail.com',
    },
    '9y7am44x': {
      'es': 'Ingrese su contraseña',
      'en': 'Enter your password',
      'fr': 'Tapez votre mot de passe',
      'it': 'Inserisci la tua password',
      'ru': 'Введите ваш пароль',
      'zh_Hant': '輸入您的密碼',
    },
    '8yvyilwz': {
      'es': 'Contraseña',
      'en': 'Password',
      'fr': 'Mot de passe',
      'it': 'Parola d\'ordine',
      'ru': 'Пароль',
      'zh_Hant': '密碼',
    },
    'tantvtdh': {
      'es': 'Ingresar',
      'en': 'Login',
      'fr': 'Entrer dans',
      'it': 'Entrare dentro',
      'ru': 'Попасть в',
      'zh_Hant': '進入',
    },
    '54sk6f0g': {
      'es': '¿Olvido su contraseña?',
      'en': 'Forgot your password?',
      'fr': 'Vous avez oublié votre mot de passe?',
      'it': 'Hai dimenticato la password?',
      'ru': 'Забыли пароль?',
      'zh_Hant': '忘記密碼了嗎？',
    },
    'lyif1ovw': {
      'es': 'Tipo de cambio Dolar',
      'en': 'Dollar exchange rate',
      'fr': 'Taux de change du dollar',
      'it': 'Tasso di cambio del dollaro',
      'ru': 'Курс доллара',
      'zh_Hant': '美元匯率',
    },
    'mh7a8kcw': {
      'es': 'Fecha:',
      'en': 'Date:',
      'fr': 'Date:',
      'it': 'Data:',
      'ru': 'Дата:',
      'zh_Hant': '日期：',
    },
    '2zamxllt': {
      'es': 'Compra:',
      'en': 'Dollar exchange rate:',
      'fr': 'Taux de change du dollar :',
      'it': 'Tasso di cambio del dollaro:',
      'ru': 'Курс доллара:',
      'zh_Hant': '美元匯率：',
    },
    'wmzfcin2': {
      'es': '\$',
      'en': '\$',
      'fr': '\$',
      'it': '\$',
      'ru': '\$',
      'zh_Hant': '\$',
    },
    'zsz48zzm': {
      'es': 'Venta:',
      'en': 'Dollar exchange rate:',
      'fr': 'Taux de change du dollar :',
      'it': 'Tasso di cambio del dollaro:',
      'ru': 'Курс доллара:',
      'zh_Hant': '美元匯率：',
    },
    'bpbnoql0': {
      'es': '\$',
      'en': '\$',
      'fr': '\$',
      'it': '\$',
      'ru': '\$',
      'zh_Hant': '\$',
    },
    'iw2jaboc': {
      'es': 'Ingresar',
      'en': 'login',
      'fr': 'connexion',
      'it': 'login',
      'ru': 'авторизоваться',
      'zh_Hant': '登錄',
    },
  },
  // AdminHomePage
  {
    'fiye4eu3': {
      'es': 'Página Principal Admin',
      'en': 'Principal Administrator',
      'fr': 'Administrateur principal',
      'it': 'Amministratore principale',
      'ru': 'Главный администратор',
      'zh_Hant': '首席行政官',
    },
    'a377c7re': {
      'es': 'Cerrar',
      'en': 'Close',
      'fr': 'Fermer',
      'it': 'Vicino',
      'ru': 'Закрывать',
      'zh_Hant': '關閉',
    },
    'ba634bsa': {
      'es': 'Menú',
      'en': 'Menu',
      'fr': 'Menu',
      'it': 'Menù',
      'ru': 'Меню',
      'zh_Hant': '菜單',
    },
    '8h1c978r': {
      'es': 'Usuarios',
      'en': 'users',
      'fr': 'utilisateurs',
      'it': 'utenti',
      'ru': 'пользователи',
      'zh_Hant': '用戶',
    },
    'h0e53zeo': {
      'es': 'Cerrar sesión',
      'en': 'Sign Out',
      'fr': 'Fermer la session',
      'it': 'cancella la sottoscrizione',
      'ru': 'выйти',
      'zh_Hant': '擱筆',
    },
    'axizxu4c': {
      'es': 'Atrás',
      'en': 'Back',
      'fr': 'Derrière',
      'it': 'Indietro',
      'ru': 'Назад',
      'zh_Hant': '後退',
    },
    'jaar82ks': {
      'es': 'Dandole una mejor vida a nuestros ancianos',
      'en': 'Giving our elderly a better life',
      'fr': 'Offrir une vie meilleure à nos aînés',
      'it': 'Dare ai nostri anziani una vita migliore',
      'ru': 'Дарим нашим пожилым людям лучшую жизнь',
      'zh_Hant': '讓我們的老人過上更好的生活',
    },
    'zexnb3ec': {
      'es': 'Compartir archivos',
      'en': 'Share files',
      'fr': 'Partager des fichiers',
      'it': 'Condividi file',
      'ru': 'Делиться файлами',
      'zh_Hant': '分享文件',
    },
    'lpj1yqpr': {
      'es': 'Lista de archivos recibidos',
      'en': 'file list',
      'fr': 'liste de fichiers',
      'it': 'elenco file',
      'ru': 'список файлов',
      'zh_Hant': '檔案清單',
    },
    'wnggy5ew': {
      'es': 'Lista de archivos enviados',
      'en': 'file list',
      'fr': 'liste de fichiers',
      'it': 'elenco file',
      'ru': 'список файлов',
      'zh_Hant': '檔案清單',
    },
    '0r113sju': {
      'es': 'Usuarios',
      'en': 'users',
      'fr': 'utilisateurs',
      'it': 'utenti',
      'ru': 'пользователи',
      'zh_Hant': '用戶',
    },
    'tms6z9hr': {
      'es': 'Cerrar sesión',
      'en': 'Sign Out',
      'fr': 'Fermer la session',
      'it': 'cancella la sottoscrizione',
      'ru': 'выйти',
      'zh_Hant': '擱筆',
    },
    'hgvwplu8': {
      'es': 'Inicio',
      'en': 'Start',
      'fr': 'Début',
      'it': 'Inizio',
      'ru': 'Начинать',
      'zh_Hant': '開始',
    },
  },
  // EveryoneForgotYourPassword
  {
    '2kocnx96': {
      'es': 'Restablecer contraseña',
      'en': 'Restore password',
      'fr': 'Restaurer le mot de passe',
      'it': 'Ripristina password',
      'ru': 'Восстановить пароль',
      'zh_Hant': '恢復密碼',
    },
    'xupa8jdz': {
      'es':
          'Enviaremos un correo con un enlace para restablecer su contraseña, por favor ingrese su correo asociado a la cuenta que desea restablecer la contraseña en el siguiente campo de texto.',
      'en':
          'We will send an email with a link to reset your password, please enter your email associated with the account you want to reset the password in the text field below.',
      'fr':
          'Nous vous enverrons un e-mail avec un lien pour réinitialiser votre mot de passe, veuillez entrer votre e-mail associé au compte dont vous souhaitez réinitialiser le mot de passe dans le champ de texte ci-dessous.',
      'it':
          'Ti invieremo un\'e-mail con un link per reimpostare la tua password, inserisci la tua e-mail associata all\'account di cui desideri reimpostare la password nel campo di testo sottostante.',
      'ru':
          'Мы отправим электронное письмо со ссылкой для сброса пароля. Введите адрес электронной почты, связанный с учетной записью, для которой вы хотите сбросить пароль, в текстовое поле ниже.',
      'zh_Hant': '我們將發送一封電子郵件，其中包含重置密碼的鏈接，請在下面的文本字段中輸入與您要重置密碼的帳戶關聯的電子郵件。',
    },
    'zzg07uk9': {
      'es': 'Ingrese su dirección de correo electrónico...',
      'en': 'Enter your email address...',
      'fr': 'Entrez votre adresse email...',
      'it': 'Inserisci il tuo indirizzo email...',
      'ru': 'Введите ваш адрес электронной почты...',
      'zh_Hant': '輸入你的電子郵箱地址...',
    },
    'qjmr8bon': {
      'es': 'Ejm: xio@gmail.com',
      'en': 'Example: xio@gmail.com',
      'fr': 'Exemple : xio@gmail.com',
      'it': 'Esempio: xio@gmail.com',
      'ru': 'Пример: xio@gmail.com',
      'zh_Hant': '示例：xio@gmail.com',
    },
    'feqx8b6v': {
      'es': 'Enviar enlace',
      'en': 'send link',
      'fr': 'envoyer un lien',
      'it': 'invia il link',
      'ru': 'Отправить ссылку',
      'zh_Hant': '發送鏈接',
    },
    'sbixvcd1': {
      'es': 'Cancelar',
      'en': 'Cancel',
      'fr': 'Annuler',
      'it': 'Annulla',
      'ru': 'Отмена',
      'zh_Hant': '取消',
    },
    'clg3egdw': {
      'es': 'Home',
      'en': 'home',
      'fr': 'maison',
      'it': 'casa',
      'ru': 'дом',
      'zh_Hant': '家',
    },
  },
  // AdminUsersPage
  {
    'g8ki0t2x': {
      'es': 'Compartir Archivos',
      'en': 'Share files',
      'fr': 'Partager des fichiers',
      'it': 'Condividi file',
      'ru': 'Делиться файлами',
      'zh_Hant': '分享文件',
    },
    'nw0ch4yl': {
      'es': 'Cerrar',
      'en': 'Close',
      'fr': 'Fermer',
      'it': 'Vicino',
      'ru': 'Закрывать',
      'zh_Hant': '關閉',
    },
    'ovuaswd2': {
      'es': 'Menú',
      'en': 'Menu',
      'fr': 'Menu',
      'it': 'Menù',
      'ru': 'Меню',
      'zh_Hant': '菜單',
    },
    'r4ffckom': {
      'es': 'Usuarios',
      'en': 'Users',
      'fr': 'utilisateurs',
      'it': 'utenti',
      'ru': 'пользователи',
      'zh_Hant': '用戶',
    },
    'ldgzykfo': {
      'es': 'Cerrar sesión',
      'en': 'Sign Out',
      'fr': 'Fermer la session',
      'it': 'cancella la sottoscrizione',
      'ru': 'выйти',
      'zh_Hant': '擱筆',
    },
    '3d7n8p7q': {
      'es': 'Atrás',
      'en': 'Back',
      'fr': 'Derrière',
      'it': 'Indietro',
      'ru': 'Назад',
      'zh_Hant': '後退',
    },
    'usb96fln': {
      'es': 'Administradores',
      'en': 'Administrators',
      'fr': 'administrateurs',
      'it': 'amministratori',
      'ru': 'администраторы',
      'zh_Hant': '管理員',
    },
    'axm3byar': {
      'es': 'Colaboradores',
      'en': 'Collaborators',
      'fr': 'Collaborateurs',
      'it': 'Collaboratori',
      'ru': 'Соавторы',
      'zh_Hant': '合作者',
    },
    '67jduxfq': {
      'es': 'Registrar usuario',
      'en': 'Signin',
      'fr': 'enregistrer l\'utilisateur',
      'it': 'registra utente',
      'ru': 'зарегистрировать пользователя',
      'zh_Hant': '註冊用戶',
    },
    'xmrofn0m': {
      'es': 'Home',
      'en': 'home',
      'fr': 'maison',
      'it': 'casa',
      'ru': 'дом',
      'zh_Hant': '家',
    },
  },
  // AdminAddUser
  {
    '8paof8xu': {
      'es': 'Agregar Usuario',
      'en': 'add user',
      'fr': 'ajouter un utilisateur',
      'it': 'Aggiungi utente',
      'ru': 'Добавить пользователя',
      'zh_Hant': '添加用戶',
    },
    'cf57v3ol': {
      'es': 'Cerrar',
      'en': 'Close',
      'fr': 'Fermer',
      'it': 'Vicino',
      'ru': 'Закрывать',
      'zh_Hant': '關閉',
    },
    '7t03q7ea': {
      'es': 'Menú',
      'en': 'Menu',
      'fr': 'Menu',
      'it': 'Menù',
      'ru': 'Меню',
      'zh_Hant': '菜單',
    },
    'zfsukzgd': {
      'es': 'Usuarios',
      'en': 'users',
      'fr': 'utilisateurs',
      'it': 'utenti',
      'ru': 'пользователи',
      'zh_Hant': '用戶',
    },
    'jbvxd3at': {
      'es': 'Cerrar sesión',
      'en': 'Sign Out',
      'fr': 'Fermer la session',
      'it': 'cancella la sottoscrizione',
      'ru': 'выйти',
      'zh_Hant': '擱筆',
    },
    'wx1pueym': {
      'es': 'Atrás',
      'en': 'Back',
      'fr': 'Derrière',
      'it': 'Indietro',
      'ru': 'Назад',
      'zh_Hant': '後退',
    },
    'yfgd20v4': {
      'es': 'Ingrese el correo electrónico valido',
      'en': 'Enter email',
      'fr': 'Entrez l\'e-mail',
      'it': 'Inserisci l\'email',
      'ru': 'Введите адрес электронной почты',
      'zh_Hant': '輸入電子郵件',
    },
    '9pf7jyim': {
      'es': 'Correo valido',
      'en': 'valid email',
      'fr': 'email valide',
      'it': 'email valida',
      'ru': 'действительный адрес электронной почты',
      'zh_Hant': '有效的電子郵件',
    },
    'he65vlf4': {
      'es': 'Ingrese una identificación',
      'en': 'Enter an ID',
      'fr': 'Entrez un identifiant',
      'it': 'Inserisci un ID',
      'ru': 'Введите идентификатор',
      'zh_Hant': '輸入一個 ID',
    },
    'qvtxy0f2': {
      'es': 'Cédula',
      'en': 'Identification card',
      'fr': 'Carte d\'identité',
      'it': 'Carta d\'identità',
      'ru': 'Идентификационная карта',
      'zh_Hant': '身份證',
    },
    'ovxq2o7x': {
      'es': 'Administrador',
      'en': 'Administrator',
      'fr': 'Administrateur',
      'it': 'Amministratore',
      'ru': 'Администратор',
      'zh_Hant': '行政人員',
    },
    'f8rwm9mm': {
      'es': 'Contador',
      'en': 'Counter',
      'fr': 'Comptoir',
      'it': 'Contatore',
      'ru': 'Прилавок',
      'zh_Hant': '櫃檯',
    },
    'tilbdisr': {
      'es': 'Usuario deshabilitado',
      'en': 'disabled user',
      'fr': 'utilisateur désactivé',
      'it': 'utente disabile',
      'ru': 'отключенный пользователь',
      'zh_Hant': '禁用用戶',
    },
    'rjyxtnvo': {
      'es': 'Seleccione el rol',
      'en': 'Select the role',
      'fr': 'Sélectionnez le rôle',
      'it': 'Seleziona il ruolo',
      'ru': 'Выберите роль',
      'zh_Hant': '選擇角色',
    },
    'mfbqfhbr': {
      'es': 'Nombre Usuario',
      'en': 'Username',
      'fr': 'Nom d\'utilisateur',
      'it': 'Nome utente',
      'ru': 'Имя пользователя',
      'zh_Hant': '用戶名',
    },
    'l45omczh': {
      'es': 'Nombre',
      'en': 'Name',
      'fr': 'nom',
      'it': 'Nome',
      'ru': 'Имя',
      'zh_Hant': '姓名',
    },
    'a7taa6qv': {
      'es': 'Número teléfono',
      'en': 'Phone number',
      'fr': 'Numéro de téléphone',
      'it': 'Numero di telefono',
      'ru': 'Номер телефона',
      'zh_Hant': '電話號碼',
    },
    'o83amorm': {
      'es': 'Teléfono',
      'en': 'Phone',
      'fr': 'nom',
      'it': 'Nome',
      'ru': 'Имя',
      'zh_Hant': '姓名',
    },
    '31vxftgl': {
      'es': 'Ingrese su contraseña mayor 6 dígitos',
      'en': 'Enter your password greater than 6 digits',
      'fr': 'Entrez votre mot de passe supérieur à 6 chiffres',
      'it': 'Inserisci la tua password superiore a 6 cifre',
      'ru': 'Введите пароль длиной более 6 цифр',
      'zh_Hant': '請輸入大於 6 位的密碼',
    },
    'etfygoil': {
      'es': 'Contraseña',
      'en': 'Password',
      'fr': 'Mot de passe',
      'it': 'Parola d\'ordine',
      'ru': 'Пароль',
      'zh_Hant': '密碼',
    },
    'jeka2xsu': {
      'es': 'Ingrese nuevamente su contraseña',
      'en': 'Enter your password again',
      'fr': 'Saisissez à nouveau votre mot de passe',
      'it': 'Inserisci di nuovo la tua password',
      'ru': 'Введите пароль еще раз',
      'zh_Hant': '再次輸入您的密碼',
    },
    '8etzoebj': {
      'es': 'Verificar contraseña',
      'en': 'Verify password',
      'fr': 'vérifier le mot de passe',
      'it': 'verifica la password',
      'ru': 'подтвердите пароль',
      'zh_Hant': '驗證密碼',
    },
    'vnuuunt7': {
      'es': 'Agregar',
      'en': 'Add',
      'fr': 'Ajouter',
      'it': 'Aggiungere',
      'ru': 'Добавлять',
      'zh_Hant': '添加',
    },
    'cojvj79w': {
      'es': 'Inicio',
      'en': 'Start',
      'fr': 'Début',
      'it': 'Inizio',
      'ru': 'Начинать',
      'zh_Hant': '開始',
    },
  },
  // CounterHomePage
  {
    '9394mqwf': {
      'es': 'Página Principal Contable',
      'en': 'Homepage',
      'fr': 'Page principal',
      'it': 'Pagina iniziale',
      'ru': 'Домашняя страница',
      'zh_Hant': '主頁',
    },
    'y8jcouj5': {
      'es': 'Cerrar',
      'en': 'Close',
      'fr': 'Fermer',
      'it': 'Vicino',
      'ru': 'Закрывать',
      'zh_Hant': '關閉',
    },
    'qrjgjdlw': {
      'es': 'Menú',
      'en': 'Menu',
      'fr': 'Menu',
      'it': 'Menù',
      'ru': 'Меню',
      'zh_Hant': '菜單',
    },
    '5pfli8e4': {
      'es': 'Cerrar sesión',
      'en': 'Sign Out',
      'fr': 'Fermer la session',
      'it': 'cancella la sottoscrizione',
      'ru': 'выйти',
      'zh_Hant': '擱筆',
    },
    'xqclqm9s': {
      'es': 'Dandole una mejor vida a nuestros ancianos',
      'en': 'Giving our elderly a better life',
      'fr': 'Offrir une vie meilleure à nos aînés',
      'it': 'Dare ai nostri anziani una vita migliore',
      'ru': 'Дарим нашим пожилым людям лучшую жизнь',
      'zh_Hant': '讓我們的老人過上更好的生活',
    },
    'xcaofddl': {
      'es': 'Compartir archivos',
      'en': 'Share files',
      'fr': 'Partager des fichiers',
      'it': 'Condividi file',
      'ru': 'Делиться файлами',
      'zh_Hant': '分享文件',
    },
    '30jlapn0': {
      'es': 'Lista archivos recibidos',
      'en': 'shared files',
      'fr': 'fichiers partagés',
      'it': 'file condivisi',
      'ru': 'общие файлы',
      'zh_Hant': '共享文件',
    },
    'yvcnc630': {
      'es': 'Lista archivos enviados',
      'en': 'shared files',
      'fr': 'fichiers partagés',
      'it': 'file condivisi',
      'ru': 'общие файлы',
      'zh_Hant': '共享文件',
    },
    'zf4s999r': {
      'es': 'Cerrar sesión',
      'en': 'Sign Out',
      'fr': 'Fermer la session',
      'it': 'cancella la sottoscrizione',
      'ru': 'выйти',
      'zh_Hant': '擱筆',
    },
    '86f3xdxl': {
      'es': 'Home',
      'en': 'home',
      'fr': 'maison',
      'it': 'casa',
      'ru': 'дом',
      'zh_Hant': '家',
    },
  },
  // AdminListUserAdmin
  {
    '4i20kq31': {
      'es': 'Lista Administradores',
      'en': 'Administrators List',
      'fr': 'Liste des administrateurs',
      'it': 'Elenco amministratori',
      'ru': 'Список администраторов',
      'zh_Hant': '管理員列表',
    },
    'r7ehbfve': {
      'es': 'Cerrar',
      'en': 'Close',
      'fr': 'Fermer',
      'it': 'Vicino',
      'ru': 'Закрывать',
      'zh_Hant': '關閉',
    },
    '91q4eixb': {
      'es': 'Menú',
      'en': 'Menu',
      'fr': 'Menu',
      'it': 'Menù',
      'ru': 'Меню',
      'zh_Hant': '菜單',
    },
    'ruxq5dsb': {
      'es': 'Usuarios',
      'en': 'users',
      'fr': 'utilisateurs',
      'it': 'utenti',
      'ru': 'пользователи',
      'zh_Hant': '用戶',
    },
    '0qxyyct5': {
      'es': 'Cerrar sesión',
      'en': 'Sign Out',
      'fr': 'Fermer la session',
      'it': 'cancella la sottoscrizione',
      'ru': 'выйти',
      'zh_Hant': '擱筆',
    },
    'm3d6r0m9': {
      'es': 'Atrás',
      'en': 'Back',
      'fr': 'Derrière',
      'it': 'Indietro',
      'ru': 'Назад',
      'zh_Hant': '後退',
    },
    'djj33jc0': {
      'es': 'Nombre: ',
      'en': 'Name:',
      'fr': 'Nom:',
      'it': 'Nome:',
      'ru': 'Имя:',
      'zh_Hant': '姓名：',
    },
    'ucrncfq7': {
      'es': 'Id: ',
      'en': 'id:',
      'fr': 'identifiant:',
      'it': 'id:',
      'ru': 'идентификатор:',
      'zh_Hant': 'ID：',
    },
    'i1og0h31': {
      'es': 'Tel: ',
      'en': 'Phone:',
      'fr': 'Téléphone:',
      'it': 'Telefono:',
      'ru': 'Телефон:',
      'zh_Hant': '電話：',
    },
    'avk4orvx': {
      'es': 'Correo:',
      'en': 'Mail:',
      'fr': 'Poster:',
      'it': 'Posta:',
      'ru': 'Почта:',
      'zh_Hant': '郵件：',
    },
    'vc2jge04': {
      'es': 'Registrar usuario',
      'en': 'register user',
      'fr': 'enregistrer l\'utilisateur',
      'it': 'registra utente',
      'ru': 'зарегистрировать пользователя',
      'zh_Hant': '註冊用戶',
    },
    '7bsv1qrm': {
      'es': 'Home',
      'en': 'home',
      'fr': 'maison',
      'it': 'casa',
      'ru': 'дом',
      'zh_Hant': '家',
    },
  },
  // AdminListUserCounter
  {
    'ej44mi3t': {
      'es': 'Lista Contadores',
      'en': 'Counters List',
      'fr': 'Liste des compteurs',
      'it': 'Elenco contatori',
      'ru': 'Список счетчиков',
      'zh_Hant': '計數器列表',
    },
    'mzqii33l': {
      'es': 'Cerrar',
      'en': 'Close',
      'fr': 'Fermer',
      'it': 'Vicino',
      'ru': 'Закрывать',
      'zh_Hant': '關閉',
    },
    'qmyu1mbd': {
      'es': 'Menú',
      'en': 'Menu',
      'fr': 'Menu',
      'it': 'Menù',
      'ru': 'Меню',
      'zh_Hant': '菜單',
    },
    'kpnm0csv': {
      'es': 'Usuarios',
      'en': 'users',
      'fr': 'utilisateurs',
      'it': 'utenti',
      'ru': 'пользователи',
      'zh_Hant': '用戶',
    },
    '6hhzvd2h': {
      'es': 'Cerrar sesión',
      'en': 'Sign Out',
      'fr': 'Fermer la session',
      'it': 'cancella la sottoscrizione',
      'ru': 'выйти',
      'zh_Hant': '擱筆',
    },
    'wd8lm1fl': {
      'es': 'Atrás',
      'en': 'Back',
      'fr': 'Derrière',
      'it': 'Indietro',
      'ru': 'Назад',
      'zh_Hant': '後退',
    },
    'ubvvs0qo': {
      'es': 'Nombre: ',
      'en': 'Name:',
      'fr': 'Nom:',
      'it': 'Nome:',
      'ru': 'Имя:',
      'zh_Hant': '姓名：',
    },
    'g9r6uwl3': {
      'es': 'Id: ',
      'en': 'id:',
      'fr': 'identifiant:',
      'it': 'id:',
      'ru': 'идентификатор:',
      'zh_Hant': 'ID：',
    },
    'nxtrv7cq': {
      'es': 'Tel: ',
      'en': 'Phone:',
      'fr': 'Téléphone:',
      'it': 'Telefono:',
      'ru': 'Телефон:',
      'zh_Hant': '電話：',
    },
    'kavhquj7': {
      'es': 'Correo:',
      'en': 'Mail:',
      'fr': 'Poster:',
      'it': 'Posta:',
      'ru': 'Почта:',
      'zh_Hant': '郵件：',
    },
    '2et7peic': {
      'es': 'Registrar usuario',
      'en': 'register user',
      'fr': 'enregistrer l\'utilisateur',
      'it': 'registra utente',
      'ru': 'зарегистрировать пользователя',
      'zh_Hant': '註冊用戶',
    },
    '9t3va395': {
      'es': 'Home',
      'en': 'home',
      'fr': 'maison',
      'it': 'casa',
      'ru': 'дом',
      'zh_Hant': '家',
    },
  },
  // AdminShareArchives
  {
    '45mxul44': {
      'es': 'Compartir Archivos',
      'en': 'Share files',
      'fr': 'Partager des fichiers',
      'it': 'Condividi file',
      'ru': 'Делиться файлами',
      'zh_Hant': '分享文件',
    },
    '272yg5ji': {
      'es': 'Cerrar',
      'en': 'Close',
      'fr': 'Fermer',
      'it': 'Vicino',
      'ru': 'Закрывать',
      'zh_Hant': '關閉',
    },
    'vhmir6er': {
      'es': 'Menú',
      'en': 'Menu',
      'fr': 'Menu',
      'it': 'Menù',
      'ru': 'Меню',
      'zh_Hant': '菜單',
    },
    'n1mfriz9': {
      'es': 'Usuarios',
      'en': 'users',
      'fr': 'utilisateurs',
      'it': 'utenti',
      'ru': 'пользователи',
      'zh_Hant': '用戶',
    },
    'umarknfn': {
      'es': 'Cerrar sesión',
      'en': 'Sign Out',
      'fr': 'Fermer la session',
      'it': 'cancella la sottoscrizione',
      'ru': 'выйти',
      'zh_Hant': '擱筆',
    },
    'kuh98aei': {
      'es': 'Atrás',
      'en': 'Back',
      'fr': 'Derrière',
      'it': 'Indietro',
      'ru': 'Назад',
      'zh_Hant': '後退',
    },
    'hggbitpx': {
      'es': 'Seleccionar tipo de archivo',
      'en': 'Select file type',
      'fr': 'Sélectionnez le type de fichier',
      'it': 'Seleziona il tipo di file',
      'ru': 'Выберите тип файла',
      'zh_Hant': '選擇文件類型',
    },
    'kobp2ktp': {
      'es': 'Excel',
      'en': 'Excel',
      'fr': 'Exceller',
      'it': 'Eccellere',
      'ru': 'Excel',
      'zh_Hant': 'Excel',
    },
    'hlywaucd': {
      'es': 'Word',
      'en': 'word',
      'fr': 'mot',
      'it': 'parola',
      'ru': 'слово',
      'zh_Hant': '單詞',
    },
    'bz5juzph': {
      'es': 'Txt',
      'en': 'txt',
      'fr': 'SMS',
      'it': 'TXT',
      'ru': 'текст',
      'zh_Hant': 'TXT',
    },
    'wnhuir6n': {
      'es': 'PDF',
      'en': 'PDF',
      'fr': 'PDF',
      'it': 'PDF',
      'ru': 'PDF',
      'zh_Hant': 'PDF',
    },
    '3gnazj8l': {
      'es': 'Imagen',
      'en': 'Image',
      'fr': 'Image',
      'it': 'Immagine',
      'ru': 'Изображение',
      'zh_Hant': '圖像',
    },
    'y67cpqiu': {
      'es': 'Video',
      'en': 'Video',
      'fr': 'Vidéo',
      'it': 'video',
      'ru': 'видео',
      'zh_Hant': '視頻',
    },
    'niocj54v': {
      'es': 'Comprimido',
      'en': 'Compressed',
      'fr': 'Comprimé',
      'it': 'Compresso',
      'ru': 'Сжатый',
      'zh_Hant': '壓縮',
    },
    'beas50my': {
      'es': 'PowerPoint',
      'en': 'PowerPoint',
      'fr': 'Power Point',
      'it': 'Presa della corrente',
      'ru': 'Силовая установка',
      'zh_Hant': '微軟幻燈片軟件',
    },
    'xx8st9qh': {
      'es': 'Seleccionar tipo de archivo',
      'en': 'Select file type',
      'fr': 'Sélectionnez le type de fichier',
      'it': 'Seleziona il tipo di file',
      'ru': 'Выберите тип файла',
      'zh_Hant': '選擇文件類型',
    },
    '9mx39keh': {
      'es': 'Por favor seleccione el tipo de archivo',
      'en': 'Please select the file type',
      'fr': 'Veuillez sélectionner le type de fichier',
      'it': 'Seleziona il tipo di file',
      'ru': 'Пожалуйста, выберите тип файла',
      'zh_Hant': '請選擇文件類型',
    },
    '8x9jxm1o': {
      'es': 'Search for an item...',
      'en': 'Search for an item...',
      'fr': 'Rechercher un article...',
      'it': 'Cerca un articolo...',
      'ru': 'Поиск элемента...',
      'zh_Hant': '搜索項目...',
    },
    '1cm212ch': {
      'es': 'Digite el nombre del archivo',
      'en': 'Enter the file name',
      'fr': 'Entrez le nom du fichier',
      'it': 'Immettere il nome del file',
      'ru': 'Введите имя файла',
      'zh_Hant': '輸入文件名',
    },
    '54rnvrga': {
      'es': 'Nombre  del Archivo ',
      'en': 'File name',
      'fr': 'Nom de fichier',
      'it': 'Nome del file',
      'ru': 'Имя файла',
      'zh_Hant': '文件名',
    },
    'mhhkmzbh': {
      'es': 'Subir archivo',
      'en': 'Upload file',
      'fr': 'Téléverser un fichier',
      'it': 'Caricare un file',
      'ru': 'Загрузить файл',
      'zh_Hant': '上傳文件',
    },
    'rcygd4gq': {
      'es': 'Regresar',
      'en': 'Go back',
      'fr': 'Retourner',
      'it': 'Torna indietro',
      'ru': 'Возвращаться',
      'zh_Hant': '回去',
    },
    'jglniszk': {
      'es': 'Home',
      'en': 'home',
      'fr': 'maison',
      'it': 'casa',
      'ru': 'дом',
      'zh_Hant': '家',
    },
  },
  // CounterListArchivesArrives
  {
    'xw9feanz': {
      'es': 'Lista de archivos recibidos',
      'en': 'Homepage',
      'fr': 'Page principal',
      'it': 'Pagina iniziale',
      'ru': 'Домашняя страница',
      'zh_Hant': '主頁',
    },
    'sdcw131e': {
      'es': 'Cerrar',
      'en': 'Close',
      'fr': 'Fermer',
      'it': 'Vicino',
      'ru': 'Закрывать',
      'zh_Hant': '關閉',
    },
    'je25mfs8': {
      'es': 'Menú',
      'en': 'Menu',
      'fr': 'Menu',
      'it': 'Menù',
      'ru': 'Меню',
      'zh_Hant': '菜單',
    },
    'm8l29kxn': {
      'es': 'Cerrar sesión',
      'en': 'Sign Out',
      'fr': 'Fermer la session',
      'it': 'cancella la sottoscrizione',
      'ru': 'выйти',
      'zh_Hant': '擱筆',
    },
    '0rbd390y': {
      'es': 'Atrás',
      'en': 'Back',
      'fr': 'Derrière',
      'it': 'Indietro',
      'ru': 'Назад',
      'zh_Hant': '後退',
    },
    '4bgvdq5w': {
      'es': 'Nombre: ',
      'en': 'Name:',
      'fr': 'Nom:',
      'it': 'Nome:',
      'ru': 'Имя:',
      'zh_Hant': '姓名：',
    },
    '6zfdc80o': {
      'es': 'Tipo:  ',
      'en': 'Guy:',
      'fr': 'Type:',
      'it': 'Tipo:',
      'ru': 'Парень:',
      'zh_Hant': '傢伙：',
    },
    'waro2pb0': {
      'es': 'Fecha:  ',
      'en': 'Date:',
      'fr': 'Date:',
      'it': 'Data:',
      'ru': 'Дата:',
      'zh_Hant': '日期：',
    },
    'fhfmd4b2': {
      'es': 'Regresar',
      'en': 'Go back',
      'fr': 'Retourner',
      'it': 'Torna indietro',
      'ru': 'Возвращаться',
      'zh_Hant': '回去',
    },
    'vhd4aw8j': {
      'es': 'Compartir',
      'en': 'Upload file',
      'fr': 'Téléverser un fichier',
      'it': 'Caricare un file',
      'ru': 'Загрузить файл',
      'zh_Hant': '上傳文件',
    },
    'b840ev68': {
      'es': 'Home',
      'en': 'home',
      'fr': 'maison',
      'it': 'casa',
      'ru': 'дом',
      'zh_Hant': '家',
    },
  },
  // AdminListArchivesArrives
  {
    '4f0swght': {
      'es': 'Lista Archivos recibidos',
      'en': 'File List',
      'fr': 'Liste de fichiers',
      'it': 'Elenco file',
      'ru': 'Список файлов',
      'zh_Hant': '檔案清單',
    },
    'qck9nhqz': {
      'es': 'Cerrar',
      'en': 'Close',
      'fr': 'Fermer',
      'it': 'Vicino',
      'ru': 'Закрывать',
      'zh_Hant': '關閉',
    },
    '7rsz2t5p': {
      'es': 'Menú',
      'en': 'Menu',
      'fr': 'Menu',
      'it': 'Menù',
      'ru': 'Меню',
      'zh_Hant': '菜單',
    },
    'a4gkf213': {
      'es': 'Usuarios',
      'en': 'users',
      'fr': 'utilisateurs',
      'it': 'utenti',
      'ru': 'пользователи',
      'zh_Hant': '用戶',
    },
    'psqdb4jo': {
      'es': 'Cerrar sesión',
      'en': 'Sign Out',
      'fr': 'Fermer la session',
      'it': 'cancella la sottoscrizione',
      'ru': 'выйти',
      'zh_Hant': '擱筆',
    },
    'wbgr0glu': {
      'es': 'Atrás',
      'en': 'Back',
      'fr': 'Derrière',
      'it': 'Indietro',
      'ru': 'Назад',
      'zh_Hant': '後退',
    },
    'tvxv5k11': {
      'es': 'Nombre: ',
      'en': 'Name:',
      'fr': 'Nom:',
      'it': 'Nome:',
      'ru': 'Имя:',
      'zh_Hant': '姓名：',
    },
    'hsjk66q7': {
      'es': 'Tipo:  ',
      'en': 'Guy:',
      'fr': 'Type:',
      'it': 'Tipo:',
      'ru': 'Парень:',
      'zh_Hant': '傢伙：',
    },
    '7zdx3h3c': {
      'es': 'Fecha:  ',
      'en': 'Date:',
      'fr': 'Date:',
      'it': 'Data:',
      'ru': 'Дата:',
      'zh_Hant': '日期：',
    },
    'thu3xxxg': {
      'es': 'Regresar',
      'en': 'Go back',
      'fr': 'Retourner',
      'it': 'Torna indietro',
      'ru': 'Возвращаться',
      'zh_Hant': '回去',
    },
    '8nqn4kjf': {
      'es': 'Compartir',
      'en': 'Upload file',
      'fr': 'Téléverser un fichier',
      'it': 'Caricare un file',
      'ru': 'Загрузить файл',
      'zh_Hant': '上傳文件',
    },
    's5obf3ai': {
      'es': 'Home',
      'en': 'home',
      'fr': 'maison',
      'it': 'casa',
      'ru': 'дом',
      'zh_Hant': '家',
    },
  },
  // CounterShareArchives
  {
    '1a933y6i': {
      'es': 'Compartir Archivos',
      'en': 'Share files',
      'fr': 'Partager des fichiers',
      'it': 'Condividi file',
      'ru': 'Делиться файлами',
      'zh_Hant': '分享文件',
    },
    'jf08zdly': {
      'es': 'Cerrar',
      'en': 'Close',
      'fr': 'Fermer',
      'it': 'Vicino',
      'ru': 'Закрывать',
      'zh_Hant': '關閉',
    },
    '5xb8t4q2': {
      'es': 'Menú',
      'en': 'Menu',
      'fr': 'Menu',
      'it': 'Menù',
      'ru': 'Меню',
      'zh_Hant': '菜單',
    },
    '25qzjitw': {
      'es': 'Cerrar sesión',
      'en': 'Sign Out',
      'fr': 'Fermer la session',
      'it': 'cancella la sottoscrizione',
      'ru': 'выйти',
      'zh_Hant': '擱筆',
    },
    'ms0x04j8': {
      'es': 'Atrás',
      'en': 'Back',
      'fr': 'Derrière',
      'it': 'Indietro',
      'ru': 'Назад',
      'zh_Hant': '後退',
    },
    '7c6atsff': {
      'es': 'Seleccionar tipo de archivo',
      'en': 'Select file type',
      'fr': 'Sélectionnez le type de fichier',
      'it': 'Seleziona il tipo di file',
      'ru': 'Выберите тип файла',
      'zh_Hant': '選擇文件類型',
    },
    'efboxf87': {
      'es': 'Excel',
      'en': 'Excel',
      'fr': 'Exceller',
      'it': 'Eccellere',
      'ru': 'Excel',
      'zh_Hant': 'Excel',
    },
    'iypd02sp': {
      'es': 'Word',
      'en': 'word',
      'fr': 'mot',
      'it': 'parola',
      'ru': 'слово',
      'zh_Hant': '單詞',
    },
    'lmsvh41v': {
      'es': 'Txt',
      'en': 'txt',
      'fr': 'SMS',
      'it': 'TXT',
      'ru': 'текст',
      'zh_Hant': 'TXT',
    },
    'u52b2730': {
      'es': 'PDF',
      'en': 'PDF',
      'fr': 'PDF',
      'it': 'PDF',
      'ru': 'PDF',
      'zh_Hant': 'PDF',
    },
    'vyymb1s7': {
      'es': 'Imagen',
      'en': 'Image',
      'fr': 'Image',
      'it': 'Immagine',
      'ru': 'Изображение',
      'zh_Hant': '圖像',
    },
    'wmcqgi5u': {
      'es': 'Video',
      'en': 'Video',
      'fr': 'Vidéo',
      'it': 'video',
      'ru': 'видео',
      'zh_Hant': '視頻',
    },
    'q99ti580': {
      'es': 'Comprimido',
      'en': 'Compressed',
      'fr': 'Comprimé',
      'it': 'Compresso',
      'ru': 'Сжатый',
      'zh_Hant': '壓縮',
    },
    'vrgbkd5c': {
      'es': 'PowerPoint',
      'en': 'PowerPoint',
      'fr': 'Power Point',
      'it': 'Presa della corrente',
      'ru': 'Силовая установка',
      'zh_Hant': '微軟幻燈片軟件',
    },
    'zx68g163': {
      'es': 'Seleccionar tipo de archivo',
      'en': 'Select file type',
      'fr': 'Sélectionnez le type de fichier',
      'it': 'Seleziona il tipo di file',
      'ru': 'Выберите тип файла',
      'zh_Hant': '選擇文件類型',
    },
    '9z7jrz0m': {
      'es': 'Por favor seleccione el tipo de archivo',
      'en': 'Please select the file type',
      'fr': 'Veuillez sélectionner le type de fichier',
      'it': 'Seleziona il tipo di file',
      'ru': 'Пожалуйста, выберите тип файла',
      'zh_Hant': '請選擇文件類型',
    },
    'wuygyzjd': {
      'es': 'Search for an item...',
      'en': 'Search for an item...',
      'fr': 'Rechercher un article...',
      'it': 'Cerca un articolo...',
      'ru': 'Поиск элемента...',
      'zh_Hant': '搜索項目...',
    },
    'b6zy8vld': {
      'es': 'Digite el nombre del archivo',
      'en': 'Enter the file name',
      'fr': 'Entrez le nom du fichier',
      'it': 'Immettere il nome del file',
      'ru': 'Введите имя файла',
      'zh_Hant': '輸入文件名',
    },
    'e2eay0be': {
      'es': 'Nombre  del Archivo ',
      'en': 'File name',
      'fr': 'Nom de fichier',
      'it': 'Nome del file',
      'ru': 'Имя файла',
      'zh_Hant': '文件名',
    },
    'lafqjvod': {
      'es': 'Subir archivo',
      'en': 'Upload file',
      'fr': 'Téléverser un fichier',
      'it': 'Caricare un file',
      'ru': 'Загрузить файл',
      'zh_Hant': '上傳文件',
    },
    'owhfo621': {
      'es': 'Regresar',
      'en': 'Go back',
      'fr': 'Retourner',
      'it': 'Torna indietro',
      'ru': 'Возвращаться',
      'zh_Hant': '回去',
    },
    'zn0cw062': {
      'es': 'Home',
      'en': 'home',
      'fr': 'maison',
      'it': 'casa',
      'ru': 'дом',
      'zh_Hant': '家',
    },
  },
  // CounterListArchivesSent
  {
    'ewk9osd8': {
      'es': 'Lista de archivos enviados',
      'en': 'Homepage',
      'fr': 'Page principal',
      'it': 'Pagina iniziale',
      'ru': 'Домашняя страница',
      'zh_Hant': '主頁',
    },
    'xj3horgh': {
      'es': 'Cerrar',
      'en': 'Close',
      'fr': 'Fermer',
      'it': 'Vicino',
      'ru': 'Закрывать',
      'zh_Hant': '關閉',
    },
    '00awl4u4': {
      'es': 'Menú',
      'en': 'Menu',
      'fr': 'Menu',
      'it': 'Menù',
      'ru': 'Меню',
      'zh_Hant': '菜單',
    },
    '24ebv9uf': {
      'es': 'Cerrar sesión',
      'en': 'Sign Out',
      'fr': 'Fermer la session',
      'it': 'cancella la sottoscrizione',
      'ru': 'выйти',
      'zh_Hant': '擱筆',
    },
    'gdp45zgf': {
      'es': 'Atrás',
      'en': 'Back',
      'fr': 'Derrière',
      'it': 'Indietro',
      'ru': 'Назад',
      'zh_Hant': '後退',
    },
    '3gkpr5w0': {
      'es': 'Nombre: ',
      'en': 'Name:',
      'fr': 'Nom:',
      'it': 'Nome:',
      'ru': 'Имя:',
      'zh_Hant': '姓名：',
    },
    'giifrkct': {
      'es': 'Tipo:  ',
      'en': 'Guy:',
      'fr': 'Type:',
      'it': 'Tipo:',
      'ru': 'Парень:',
      'zh_Hant': '傢伙：',
    },
    'gcfysevg': {
      'es': 'Fecha:  ',
      'en': 'Date:',
      'fr': 'Date:',
      'it': 'Data:',
      'ru': 'Дата:',
      'zh_Hant': '日期：',
    },
    'yf8ge4fh': {
      'es': 'Regresar',
      'en': 'Go back',
      'fr': 'Retourner',
      'it': 'Torna indietro',
      'ru': 'Возвращаться',
      'zh_Hant': '回去',
    },
    '9i92d9zu': {
      'es': 'Compartir',
      'en': 'Upload file',
      'fr': 'Téléverser un fichier',
      'it': 'Caricare un file',
      'ru': 'Загрузить файл',
      'zh_Hant': '上傳文件',
    },
    'duq448xe': {
      'es': 'Home',
      'en': 'home',
      'fr': 'maison',
      'it': 'casa',
      'ru': 'дом',
      'zh_Hant': '家',
    },
  },
  // AdminListArchivesSent
  {
    '1pigps4b': {
      'es': 'Lista Archivos enviados',
      'en': 'File List',
      'fr': 'Liste de fichiers',
      'it': 'Elenco file',
      'ru': 'Список файлов',
      'zh_Hant': '檔案清單',
    },
    'kd75pm3r': {
      'es': 'Cerrar',
      'en': 'Close',
      'fr': 'Fermer',
      'it': 'Vicino',
      'ru': 'Закрывать',
      'zh_Hant': '關閉',
    },
    '8i5ztotl': {
      'es': 'Menú',
      'en': 'Menu',
      'fr': 'Menu',
      'it': 'Menù',
      'ru': 'Меню',
      'zh_Hant': '菜單',
    },
    'i1gf3sey': {
      'es': 'Usuarios',
      'en': 'users',
      'fr': 'utilisateurs',
      'it': 'utenti',
      'ru': 'пользователи',
      'zh_Hant': '用戶',
    },
    'aq4sum5m': {
      'es': 'Cerrar sesión',
      'en': 'Sign Out',
      'fr': 'Fermer la session',
      'it': 'cancella la sottoscrizione',
      'ru': 'выйти',
      'zh_Hant': '擱筆',
    },
    'uprqa41s': {
      'es': 'Atrás',
      'en': 'Back',
      'fr': 'Derrière',
      'it': 'Indietro',
      'ru': 'Назад',
      'zh_Hant': '後退',
    },
    'wan3tuvn': {
      'es': 'Nombre: ',
      'en': 'Name:',
      'fr': 'Nom:',
      'it': 'Nome:',
      'ru': 'Имя:',
      'zh_Hant': '姓名：',
    },
    'a2a2z93h': {
      'es': 'Tipo:  ',
      'en': 'Guy:',
      'fr': 'Type:',
      'it': 'Tipo:',
      'ru': 'Парень:',
      'zh_Hant': '傢伙：',
    },
    'b5y3ki35': {
      'es': 'Fecha:  ',
      'en': 'Date:',
      'fr': 'Date:',
      'it': 'Data:',
      'ru': 'Дата:',
      'zh_Hant': '日期：',
    },
    'nv941p3g': {
      'es': 'Regresar',
      'en': 'Go back',
      'fr': 'Retourner',
      'it': 'Torna indietro',
      'ru': 'Возвращаться',
      'zh_Hant': '回去',
    },
    'z7kh2lid': {
      'es': 'Compartir',
      'en': 'Upload file',
      'fr': 'Téléverser un fichier',
      'it': 'Caricare un file',
      'ru': 'Загрузить файл',
      'zh_Hant': '上傳文件',
    },
    'y06ncbwi': {
      'es': 'Home',
      'en': 'home',
      'fr': 'maison',
      'it': 'casa',
      'ru': 'дом',
      'zh_Hant': '家',
    },
  },
  // EditUserAdmin
  {
    'avwnbvz9': {
      'es': 'Editemos abajo digitando y seleccionando:',
      'en': 'Let\'s edit below by typing and selecting:',
      'fr': 'Modifions ci-dessous en tapant et en sélectionnant :',
      'it': 'Modifichiamo di seguito digitando e selezionando:',
      'ru': 'Давайте отредактируем ниже, набрав и выбрав:',
      'zh_Hant': '讓我們通過鍵入和選擇在下面進行編輯：',
    },
    'r20a38od': {
      'es': 'Identificación: ',
      'en': 'ID:',
      'fr': 'IDENTIFIANT:',
      'it': 'ID:',
      'ru': 'ИДЕНТИФИКАТОР:',
      'zh_Hant': 'ID：',
    },
    'bk9dvvzj': {
      'es': 'Nombre de usuario: ',
      'en': 'Username:',
      'fr': 'Nom d\'utilisateur:',
      'it': 'Nome utente:',
      'ru': 'Имя пользователя:',
      'zh_Hant': '用戶名：',
    },
    '1ylqqn3d': {
      'es': 'Teléfono:',
      'en': 'Phone:',
      'fr': 'Téléphone:',
      'it': 'Telefono:',
      'ru': 'Телефон:',
      'zh_Hant': '電話：',
    },
    'mj2xdayh': {
      'es': 'Administrador',
      'en': 'Administrator',
      'fr': 'Administrateur',
      'it': 'Amministratore',
      'ru': 'Администратор',
      'zh_Hant': '行政人員',
    },
    'xwmnx8u4': {
      'es': 'Contador',
      'en': 'Counter',
      'fr': 'Comptoir',
      'it': 'Contatore',
      'ru': 'Прилавок',
      'zh_Hant': '櫃檯',
    },
    '5a8kfgxp': {
      'es': 'Usuario deshabilitado',
      'en': 'disabled user',
      'fr': 'utilisateur désactivé',
      'it': 'utente disabile',
      'ru': 'отключенный пользователь',
      'zh_Hant': '禁用用戶',
    },
    'suq2o69q': {
      'es': 'Seleccione el rol',
      'en': 'Select the role',
      'fr': 'Sélectionnez le rôle',
      'it': 'Seleziona il ruolo',
      'ru': 'Выберите роль',
      'zh_Hant': '選擇角色',
    },
    'hks3j54u': {
      'es': 'Editar',
      'en': 'Edit',
      'fr': 'Modifier',
      'it': 'Modificare',
      'ru': 'Редактировать',
      'zh_Hant': '編輯',
    },
    'w6e05qwl': {
      'es': 'Cancelar',
      'en': 'Cancel',
      'fr': 'Annuler',
      'it': 'Annulla',
      'ru': 'Отмена',
      'zh_Hant': '取消',
    },
  },
  // EditUserCounter
  {
    'x7ut0xhz': {
      'es': 'Editemos abajo digitando y seleccionando:',
      'en': 'Let\'s edit below by typing and selecting:',
      'fr': 'Modifions ci-dessous en tapant et en sélectionnant :',
      'it': 'Modifichiamo di seguito digitando e selezionando:',
      'ru': 'Давайте отредактируем ниже, набрав и выбрав:',
      'zh_Hant': '讓我們通過鍵入和選擇在下面進行編輯：',
    },
    'giljnfjc': {
      'es': 'Identificación: ',
      'en': 'ID:',
      'fr': 'IDENTIFIANT:',
      'it': 'ID:',
      'ru': 'ИДЕНТИФИКАТОР:',
      'zh_Hant': 'ID：',
    },
    '8jtn4bp8': {
      'es': 'Nombre de usuario: ',
      'en': 'Username:',
      'fr': 'Nom d\'utilisateur:',
      'it': 'Nome utente:',
      'ru': 'Имя пользователя:',
      'zh_Hant': '用戶名：',
    },
    'bbupehwm': {
      'es': 'Teléfono:',
      'en': 'Phone:',
      'fr': 'Téléphone:',
      'it': 'Telefono:',
      'ru': 'Телефон:',
      'zh_Hant': '電話：',
    },
    'ayds286g': {
      'es': 'Administrador',
      'en': 'Administrator',
      'fr': 'Administrateur',
      'it': 'Amministratore',
      'ru': 'Администратор',
      'zh_Hant': '行政人員',
    },
    '9hzyq6q5': {
      'es': 'Contador',
      'en': 'Counter',
      'fr': 'Comptoir',
      'it': 'Contatore',
      'ru': 'Прилавок',
      'zh_Hant': '櫃檯',
    },
    'xtu7mdai': {
      'es': 'Usuario deshabilitado',
      'en': 'disabled user',
      'fr': 'utilisateur désactivé',
      'it': 'utente disabile',
      'ru': 'отключенный пользователь',
      'zh_Hant': '禁用用戶',
    },
    '0kche651': {
      'es': 'Seleccione el rol',
      'en': 'Select the role',
      'fr': 'Sélectionnez le rôle',
      'it': 'Seleziona il ruolo',
      'ru': 'Выберите роль',
      'zh_Hant': '選擇角色',
    },
    'yi1onhmo': {
      'es': 'Editar',
      'en': 'Edit',
      'fr': 'Modifier',
      'it': 'Modificare',
      'ru': 'Редактировать',
      'zh_Hant': '編輯',
    },
    'f9sg0lwr': {
      'es': 'Cancelar',
      'en': 'Cancel',
      'fr': 'Annuler',
      'it': 'Annulla',
      'ru': 'Отмена',
      'zh_Hant': '取消',
    },
  },
  // Miscellaneous
  {
    '0t51txt8': {
      'es': 'La app necesita obtener acceso a la camara',
      'en': 'The app needs to get access to the camera',
      'fr': 'L\'application doit avoir accès à la caméra',
      'it': 'L\'app deve avere accesso alla fotocamera',
      'ru': 'Приложению необходимо получить доступ к камере',
      'zh_Hant': '該應用程序需要訪問相機',
    },
    '61g48s0z': {
      'es': 'La app necesita obtener acceso a Bluetooth',
      'en': 'The app needs to get access to Bluetooth',
      'fr': 'L\'application doit avoir accès au Bluetooth',
      'it': 'L\'app deve avere accesso al Bluetooth',
      'ru': 'Приложению необходимо получить доступ к Bluetooth',
      'zh_Hant': '該應用程序需要訪問藍牙',
    },
    '9pxf09j9': {
      'es': '',
      'en': '',
      'fr': '',
      'it': '',
      'ru': '',
      'zh_Hant': '',
    },
    'ykf8vou8': {
      'es': '',
      'en': '',
      'fr': '',
      'it': '',
      'ru': '',
      'zh_Hant': '',
    },
    'zki5i2tn': {
      'es': '',
      'en': '',
      'fr': '',
      'it': '',
      'ru': '',
      'zh_Hant': '',
    },
    '9xvw7h0p': {
      'es': '',
      'en': '',
      'fr': '',
      'it': '',
      'ru': '',
      'zh_Hant': '',
    },
    '7lz3at95': {
      'es': '',
      'en': '',
      'fr': '',
      'it': '',
      'ru': '',
      'zh_Hant': '',
    },
    'cakm2lh4': {
      'es': '',
      'en': '',
      'fr': '',
      'it': '',
      'ru': '',
      'zh_Hant': '',
    },
    '01x99lac': {
      'es': '',
      'en': '',
      'fr': '',
      'it': '',
      'ru': '',
      'zh_Hant': '',
    },
    'qukr4nk0': {
      'es': '',
      'en': '',
      'fr': '',
      'it': '',
      'ru': '',
      'zh_Hant': '',
    },
    'bymytxnn': {
      'es': '',
      'en': '',
      'fr': '',
      'it': '',
      'ru': '',
      'zh_Hant': '',
    },
    '0v6s90jz': {
      'es': '',
      'en': '',
      'fr': '',
      'it': '',
      'ru': '',
      'zh_Hant': '',
    },
    'mdebsak9': {
      'es': '',
      'en': '',
      'fr': '',
      'it': '',
      'ru': '',
      'zh_Hant': '',
    },
    '2ornpvat': {
      'es': '',
      'en': '',
      'fr': '',
      'it': '',
      'ru': '',
      'zh_Hant': '',
    },
    'gmcm81oj': {
      'es': '',
      'en': '',
      'fr': '',
      'it': '',
      'ru': '',
      'zh_Hant': '',
    },
    'zhh2b8p7': {
      'es': '',
      'en': '',
      'fr': '',
      'it': '',
      'ru': '',
      'zh_Hant': '',
    },
    '60r7qy8p': {
      'es': '',
      'en': '',
      'fr': '',
      'it': '',
      'ru': '',
      'zh_Hant': '',
    },
    '9s8h6ytq': {
      'es': '',
      'en': '',
      'fr': '',
      'it': '',
      'ru': '',
      'zh_Hant': '',
    },
    'ryrhdepy': {
      'es': '',
      'en': '',
      'fr': '',
      'it': '',
      'ru': '',
      'zh_Hant': '',
    },
    'k54s6xgh': {
      'es': '',
      'en': '',
      'fr': '',
      'it': '',
      'ru': '',
      'zh_Hant': '',
    },
    'ui8ssk95': {
      'es': '',
      'en': '',
      'fr': '',
      'it': '',
      'ru': '',
      'zh_Hant': '',
    },
    'k1xmrfem': {
      'es': '',
      'en': '',
      'fr': '',
      'it': '',
      'ru': '',
      'zh_Hant': '',
    },
    '2z1dmm74': {
      'es': '',
      'en': '',
      'fr': '',
      'it': '',
      'ru': '',
      'zh_Hant': '',
    },
  },
].reduce((a, b) => a..addAll(b));
